# Generated by Django 3.1.5 on 2021-02-22 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('one_serving_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=32, null=True)),
                ('one_serving_description', models.CharField(blank=True, max_length=40, null=True)),
                ('upc_code', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'foods_foods',
            },
        ),
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('dv_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('article_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_citations', models.TextField(blank=True, null=True)),
                ('description_src_note', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'foods_nutrients',
                'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('dv_qty'), nulls_last=True), django.db.models.expressions.OrderBy(django.db.models.expressions.F('dv_unit'), nulls_last=True)],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('abbr', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'foods_units',
            },
        ),
        migrations.CreateModel(
            name='USDACategory',
            fields=[
                ('name', models.CharField(max_length=40, unique=True)),
                ('usdacategory_id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('search_order', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'foods_usdacategories',
            },
        ),
        migrations.CreateModel(
            name='USDAFood',
            fields=[
                ('fdc_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'foods_usdafoods',
            },
        ),
        migrations.CreateModel(
            name='USDANutrient',
            fields=[
                ('usdanutrient_id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'db_table': 'foods_usdanutrients',
            },
        ),
        migrations.CreateModel(
            name='UserAddedFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='foods.food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'foods_useraddedfoods',
            },
        ),
        migrations.CreateModel(
            name='UnitConversion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_conversion_coefficient', models.DecimalField(decimal_places=15, max_digits=45)),
                ('from_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_unit', to='foods.unit')),
                ('to_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_unit', to='foods.unit')),
            ],
            options={
                'db_table': 'foods_unit_conversions',
            },
        ),
        migrations.CreateModel(
            name='NutritionFact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nutrient_qty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.food')),
                ('nutrient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_nutrition_facts', to='foods.nutrient')),
            ],
            options={
                'db_table': 'foods_nutrition_facts',
            },
        ),
        migrations.AddField(
            model_name='nutrient',
            name='dv_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='foods.unit'),
        ),
        migrations.AddField(
            model_name='nutrient',
            name='usdanutrients',
            field=models.ManyToManyField(blank=True, to='foods.USDANutrient'),
        ),
        migrations.CreateModel(
            name='FoodUSDAFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.ForeignKey(db_column='food_id', on_delete=django.db.models.deletion.CASCADE, to='foods.food')),
                ('usdafood', models.OneToOneField(db_column='fdc_id', on_delete=django.db.models.deletion.CASCADE, to='foods.usdafood')),
            ],
            options={
                'db_table': 'foods_foods_usdafoods',
            },
        ),
        migrations.AddField(
            model_name='food',
            name='nutrients',
            field=models.ManyToManyField(blank=True, through='foods.NutritionFact', to='foods.Nutrient'),
        ),
        migrations.AddField(
            model_name='food',
            name='one_serving_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='foods.unit'),
        ),
        migrations.AddField(
            model_name='food',
            name='usdacategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='foods.usdacategory'),
        ),
        migrations.AddField(
            model_name='food',
            name='usdafoods',
            field=models.ManyToManyField(blank=True, through='foods.FoodUSDAFood', to='foods.USDAFood'),
        ),
    ]
