# Generated by Django 3.1.5 on 2021-01-26 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('one_serving_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('one_serving_display_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('one_serving_display_unit', models.CharField(blank=True, max_length=30)),
                ('usda_fdc_id', models.IntegerField(blank=True)),
                ('upc_code', models.IntegerField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('dv_qty', models.DecimalField(decimal_places=2, max_digits=7)),
                ('usda_nutrient_id', models.IntegerField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('abbr', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='USDACategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('usda_category_id', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UnitConversion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_conversion_coefficient', models.DecimalField(decimal_places=15, max_digits=45)),
                ('from_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_unit', to='foods.unit')),
                ('to_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_unit', to='foods.unit')),
            ],
        ),
        migrations.CreateModel(
            name='NutritionFact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nutrient_qty', models.DecimalField(decimal_places=2, max_digits=7)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.food')),
                ('nutrient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.nutrient')),
            ],
        ),
        migrations.AddField(
            model_name='nutrient',
            name='dv_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='foods.unit'),
        ),
        migrations.CreateModel(
            name='FoodAddedByUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='foods.food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='users.user')),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='nutrients',
            field=models.ManyToManyField(through='foods.NutritionFact', to='foods.Nutrient'),
        ),
        migrations.AddField(
            model_name='food',
            name='one_serving_unit',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='foods.unit'),
        ),
        migrations.AddField(
            model_name='food',
            name='usda_category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='foods.usdacategory'),
        ),
    ]
