# Generated by Django 3.1.5 on 2021-01-27 22:46

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('one_serving_qty', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('one_serving_display_qty', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('one_serving_display_unit', models.CharField(max_length=30, null=True)),
                ('usda_fdc_id', models.IntegerField(null=True)),
                ('upc_code', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': '"foods_foods"',
            },
        ),
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('dv_qty', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('article_url', models.URLField(null=True)),
                ('description', models.TextField(null=True)),
                ('description_citations', models.TextField(null=True)),
                ('description_src_note', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': '"foods_nutrients"',
                'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('dv_qty'), nulls_last=True), django.db.models.expressions.OrderBy(django.db.models.expressions.F('dv_unit'), nulls_last=True)],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('abbr', models.CharField(max_length=10)),
            ],
            options={
                'db_table': '"foods_units"',
            },
        ),
        migrations.CreateModel(
            name='USDACategory',
            fields=[
                ('name', models.CharField(max_length=40, unique=True)),
                ('usdacategory_id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': '"foods_usdacategories"',
            },
        ),
        migrations.CreateModel(
            name='USDANutrient',
            fields=[
                ('usdanutrient_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'db_table': '"foods_usdanutrients"',
            },
        ),
        migrations.CreateModel(
            name='UnitConversion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_conversion_coefficient', models.DecimalField(decimal_places=15, max_digits=45)),
                ('from_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_unit', to='foods.unit')),
                ('to_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_unit', to='foods.unit')),
            ],
            options={
                'db_table': '"foods_unit_conversions"',
            },
        ),
        migrations.CreateModel(
            name='NutritionFact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nutrient_qty', models.DecimalField(decimal_places=2, max_digits=7)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.food')),
                ('nutrient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.nutrient')),
            ],
            options={
                'db_table': '"foods_nutrition_facts"',
            },
        ),
        migrations.AddField(
            model_name='nutrient',
            name='dv_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='foods.unit'),
        ),
        migrations.AddField(
            model_name='nutrient',
            name='usdanutrients',
            field=models.ManyToManyField(blank=True, to='foods.USDANutrient'),
        ),
        migrations.CreateModel(
            name='FoodAddedByUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='foods.food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='users.user')),
            ],
            options={
                'db_table': '"foods_foods_added_by_users"',
            },
        ),
        migrations.AddField(
            model_name='food',
            name='nutrients',
            field=models.ManyToManyField(blank=True, through='foods.NutritionFact', to='foods.Nutrient'),
        ),
        migrations.AddField(
            model_name='food',
            name='one_serving_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='foods.unit'),
        ),
        migrations.AddField(
            model_name='food',
            name='usdacategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='foods.usdacategory'),
        ),
    ]
