# Generated by Django 3.1.5 on 2021-01-30 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionfact',
            name='nutrient_qty',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
