# Generated by Django 3.1.5 on 2021-05-03 20:32

from django.db import migrations
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nutrient',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='usdacategory',
            options={'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('search_order'), nulls_last=True)]},
        ),
    ]
