# Generated by Django 3.1.5 on 2021-01-28 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='USDAFood',
            fields=[
                ('fdc_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': '"foods_usdafoods"',
            },
        ),
        migrations.RemoveField(
            model_name='food',
            name='usda_fdc_id',
        ),
        migrations.CreateModel(
            name='FoodUSDAFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.OneToOneField(db_column='food_id', on_delete=django.db.models.deletion.CASCADE, to='foods.food')),
                ('usdafood', models.OneToOneField(db_column='fdc_id', on_delete=django.db.models.deletion.CASCADE, to='foods.usdafood')),
            ],
            options={
                'db_table': '"foods_foods_usdafoods"',
            },
        ),
        migrations.AddField(
            model_name='food',
            name='usdafoods',
            field=models.ManyToManyField(blank=True, through='foods.FoodUSDAFood', to='foods.USDAFood'),
        ),
    ]
