# Generated by Django 3.1.5 on 2021-01-28 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('foods', '0002_create_usdafood'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FoodAddedByUser',
            new_name='UserAddedFood',
        ),
        migrations.AlterModelTable(
            name='useraddedfood',
            table='"foods_useraddedfoods"',
        ),
    ]
