# Generated by Django 3.1.5 on 2021-02-16 04:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'recipes_allergens',
            },
        ),
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'recipes_cuisines',
            },
        ),
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'recipes_diets',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_numerator', models.PositiveSmallIntegerField()),
                ('qty_denominator', models.PositiveSmallIntegerField(default=1)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.food')),
                ('qty_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foods.unit')),
            ],
            options={
                'db_table': 'recipes_ingredients',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('author', models.CharField(max_length=50, null=True)),
                ('servings_count', models.PositiveSmallIntegerField(null=True)),
                ('prep_time', models.DurationField(null=True)),
                ('cook_time', models.DurationField(null=True)),
                ('total_time', models.DurationField(null=True)),
                ('description', models.TextField(null=True)),
                ('url', models.URLField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'recipes_recipes',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('website', models.URLField()),
            ],
            options={
                'db_table': 'recipes_recipe_sources',
            },
        ),
        migrations.CreateModel(
            name='RecipePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.photo')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
            options={
                'db_table': 'recipes_recipes_photos',
            },
        ),
        migrations.CreateModel(
            name='RecipeInternetImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internet_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.internetimage')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
            options={
                'db_table': 'recipes_recipes_internet_images',
            },
        ),
        migrations.CreateModel(
            name='RecipeDiet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.diet')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
            options={
                'db_table': 'recipes_recipes_diets',
            },
        ),
        migrations.CreateModel(
            name='RecipeCuisine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.cuisine')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
            options={
                'db_table': 'recipes_recipes_cuisines',
            },
        ),
        migrations.CreateModel(
            name='RecipeAllergen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contains_allergen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.allergen')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
            options={
                'db_table': 'recipes_recipes_allergens',
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='contains_allergens',
            field=models.ManyToManyField(blank=True, through='recipes.RecipeAllergen', to='recipes.Allergen'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='cuisines',
            field=models.ManyToManyField(blank=True, through='recipes.RecipeCuisine', to='recipes.Cuisine'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='diets',
            field=models.ManyToManyField(blank=True, through='recipes.RecipeDiet', to='recipes.Diet'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(blank=True, through='recipes.Ingredient', to='foods.Food'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='internet_images',
            field=models.ManyToManyField(blank=True, through='recipes.RecipeInternetImage', to='media.InternetImage'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipe',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='recipes.source'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='user_photos',
            field=models.ManyToManyField(blank=True, through='recipes.RecipePhoto', to='media.Photo'),
        ),
        migrations.CreateModel(
            name='NutritionFact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nutrient_qty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('nutrient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_nutrition_facts', to='foods.nutrient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
            options={
                'db_table': 'recipes_nutrition_facts',
            },
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe'),
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.PositiveSmallIntegerField()),
                ('text', models.TextField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
            options={
                'db_table': 'recipes_directions',
            },
        ),
    ]
