# Generated by Django 3.1.5 on 2021-08-12 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('date_published', models.DateField()),
            ],
            options={
                'db_table': 'accounts_privacy_policies',
            },
        ),
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('date_published', models.DateField()),
            ],
            options={
                'db_table': 'accounts_terms',
            },
        ),
        migrations.CreateModel(
            name='UserTerms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_agreed', models.DateTimeField(auto_now_add=True)),
                ('terms', models.ForeignKey(db_column='terms_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.terms')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_user_terms',
            },
        ),
        migrations.CreateModel(
            name='UserPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_agreed', models.DateTimeField(auto_now_add=True)),
                ('policy', models.ForeignKey(db_column='policy_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.privacypolicy')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_user_policies',
            },
        ),
    ]
